const tabela = [
  {
    nome: "Corinthians",
    sigla: "CRC",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Fluminense",
    sigla: "FLU",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Atletico",
    sigla: "ATL",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Gremio",
    sigla: "GMO",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Sao-Paulo",
    sigla: "SAP",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Flamengo",
    sigla: "FLA",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Botafogo",
    sigla: "BTG",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Palmeiras",
    sigla: "PAL",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Santos ",
    sigla: "SAN",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Mirassol ",
    sigla: "MIR",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Ceará  ",
    sigla: "CEA",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Sport",
    sigla: "SPT",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Fortaleza",
    sigla: "FOT",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Internacional",
    sigla: "INT",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Cruzeiro",
    sigla: "CRU",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Vasco",
    sigla: "VAS",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Bragantino",
    sigla: "BRG",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Juventude",
    sigla: "JUV",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Bahia",
    sigla: "BAH",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
  {
    nome: "Barcelona",
    sigla: "BAR",
    pontos: 0,
    vitorias: 0,
    empates: 0,
    derrotas: 0,
    golsMarcados: 0,
    golSofridos: 0,
    saldoGols: 0,
  },
];

export default tabela;
